[package]
name = "uu_false"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "false ~ (uutils) do nothing and fail"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/false"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/false.rs"

[dependencies]
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "false"
path = "src/main.rs"
