[package]
name = "uu_od"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "od ~ (uutils) display formatted representation of input"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/od"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/od.rs"

[dependencies]
byteorder = "1.3.2"
getopts = "0.2.18"
half = "1.6"
libc = "0.2.42"
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.4", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "od"
path = "src/main.rs"
