[package]
name = "uu_date"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "date ~ (uutils) display or set the current time"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/date"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/date.rs"

[dependencies]
chrono = "0.4.4"
clap = "2.32"
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "date"
path = "src/main.rs"
