[package]
name = "df"
version = "0.0.1"
authors = []

[lib]
name = "uu_df"
path = "df.rs"

[dependencies]
clap = "2.32"
libc = "0.2"
uucore = "0.0.1"

[target.'cfg(target_os = "windows")'.dependencies]
kernel32-sys = "0.2"
winapi = { version = "0.3", features = ["handleapi"] }

[[bin]]
name = "df"
path = "main.rs"
