[package]
name = "df"
version = "0.0.1"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_df"
path = "src/df.rs"

[dependencies]
clap = "2.32"
libc = "0.2"
number_prefix = "0.2"
uucore = "0.0.2"

[target.'cfg(target_os = "windows")'.dependencies]
kernel32-sys = "0.2"
winapi = { version = "0.3", features = ["handleapi", "winerror"] }

[[bin]]
name = "df"
path = "../../common/uumain.rs"
