[package]
name = "uu_sort"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "sort ~ (uutils) sort input lines"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/sort"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/sort.rs"

[dependencies]
clap = "2.33"
itertools = "0.8.0"
semver = "0.9.0"
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["fs"] }

[[bin]]
name = "sort"
path = "src/main.rs"
