[package]
name = "uu_truncate"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "truncate ~ (uutils) truncate (or extend) FILE to SIZE"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/truncate"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/truncate.rs"

[dependencies]
clap = "2.33"
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "truncate"
path = "src/main.rs"
