[package]
name = "uu_fold"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "fold ~ (uutils) wrap each line of input"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/fold"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/fold.rs"

[dependencies]
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "fold"
path = "src/main.rs"
