[package]
name = "uu_tail"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "tail ~ (uutils) display the last lines of input"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/tail"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/tail.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"

[[bin]]
name = "tail"
path = "src/main.rs"
