[package]
name = "shuf"
version = "0.0.1"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_shuf"
path = "src/shuf.rs"

[dependencies]
getopts = "0.2.18"
rand = "0.6"
uucore = "0.0.2"

[[bin]]
name = "shuf"
path = "../../common/uumain.rs"
