[package]
name = "more"
version = "0.0.1"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_more"
path = "src/more.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_termios = "0.1"
redox_syscall = "0.1"

[target.'cfg(all(unix, not(target_os = "fuchsia")))'.dependencies]
nix = "0.17"

[[bin]]
name = "more"
path = "../../common/uumain.rs"
