[package]
name = "uu_printf"
version = "0.0.1"
authors = [
    "Nathan Ross",
    "uutils developers",
]
license = "MIT"
description = "printf ~ (uutils) FORMAT and display ARGUMENTS"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/printf"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/printf.rs"

[dependencies]
itertools = "0.8.0"
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "printf"
path = "src/main.rs"
