[package]
name = "uu_yes"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "yes ~ (uutils) repeatedly display a line with STRING (or 'y')"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/yes"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/yes.rs"

[dependencies]
clap = "2.32"
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["zero-copy"] }

[features]
default = []
#
latency = []

[[bin]]
name = "yes"
path = "src/main.rs"
